### PR TITLE
add missing travel modes

### PR DESCRIPTION
**Pull request by screenagerbe**
I've added the missing travel_mode's, mostly because I'm using an e-bike for commuting  🙂

### CODE REVIEW

**Comment by eifinger** [comment]
Thank you!
Could you please format the code using [black](https://github.com/psf/black) (`black custom_components`)?

**Comment by screenagerbe** [comment]
I just realized I forgot to adjust the README.md file to include the new travel_mode's. 
Does it matter ?

**Comment by eifinger** [comment]
I will add these when this integration gets a revamp. I plan to include a configflow for UI setup etc

**Comment by screenagerbe** [comment]
ah great!
If you need someone testing the changes, let me know. 🙂

**Pull request merged**
